# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    messenger: true
    driver: "gd"
    webp:
        generate: true

    filter_sets:
        entry_thumb:
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [380, 380], mode: inset }
        avatar_thumb:
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: fixed }
        post_thumb:
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [600, 500], mode: inset }
        user_cover:
            quality: 90
            filters:
                auto_rotate: ~
                thumbnail: { size: [1500, 500], mode: fixed }

    data_loader: kbin.liip_loader
      #cache: kbin.liip_resolver

    loaders:
        kbin.liip_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

    resolvers:
        kbin.liip_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: "%uploads_base_url%"
                cache_prefix: media/cache
                visibility: public
