framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: "sync://"
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 5
                    delay: 2350
                    multiplier: 4
                    max_delay: 1800000
                serializer: messenger.transport.symfony_serializer
            async_ap:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 5
                    delay: 2350
                    multiplier: 4
                    max_delay: 1800000
                serializer: messenger.transport.symfony_serializer
            failed:
                dsn: "doctrine://default?queue_name=failed"
                retry_strategy:
                    max_retries: 10
                    delay: 20000
                    multiplier: 2
                    max_delay: 3600000
                serializer: messenger.transport.symfony_serializer
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            liip_imagine: '%env(MESSENGER_TRANSPORT_IMG_DSN)%'

        routing:
            # Route your messages to the transports
            App\Message\Contracts\AsyncMessageInterface: async
            App\Message\Contracts\AsyncApMessageInterface: async_ap
            # Consider adding SendEmail from Mailer via async messenger as well:
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Route your messages to the transports
            'Liip\ImagineBundle\Message\WarmupCache': liip_imagine
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
